### ISSUE TITLE
Upgrade to CFFI 1.1.x

### ISSUE THREAD

**Issue by thedrow** [larsks/python-signalfd#1]
CFFI now has a new major release with a little bit of breaking changes.
This library needs to either support both 0.9.x and 1.1.x or just drop 0.9 support altogether.

**Comment by larsks** [comment]
Do you have details on what breaks?  The `example.py` script in this repository seems to run fine with CFFI 1.1.2.  I haven't tested beyond that.

**Comment by thedrow** [comment]
Instead of using `verify()` which is now deprecated you should be using `set_source()` instead.
They also removed the compilation on import feature since it was causing more trouble than it's worth.
PyPy 2.6.0 works with CFF > 1.0.
See the [beta notice](http://morepypy.blogspot.co.il/2015/05/cffi-10-beta-1.html) and the [documentation](http://cffi.readthedocs.org/en/latest/overview.html) for examples.

**Comment by larsks** [comment]
The code in this module does not currently make use of the `verify()` method, and in fact the usage in this module matches that given as an example in the documentation for CFFI 1.1.2, in the "Example usage" of the `cffi.FFI` class:

```
Example usage:

    ffi = FFI()
    ffi.cdef("""
        int printf(const char *, ...);
    """)

    C = ffi.dlopen(None)   # standard library
```

If you are using this module and something isn't working correctly, let me know and I'm happy to make the necessary changes.

**Comment by thedrow** [comment]
Oh in that case everything is fine. Thanks!
